### ISSUE TITLE
Cast error with wrong argument types

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/xml-interpolator#15]
```scala
xml"""<foo bar=${67}/>"""
```

fails a cast 
```
An exception occurred while executing macro expansion
[error]     |Expr: 67
[error]     |did not conform to type: Option[Seq[xml.Node]]
[error]     |
[error]     |scala.tasty.reflect.ExprCastError: Expr: 67
[error]     |did not conform to type: Option[Seq[xml.Node]]
[error]     |
[error]     |   at dotty.tools.dotc.tastyreflect.KernelImpl.QuotedExpr_cast(KernelImpl.scala:1750)
[error]     |   at dotty.tools.dotc.tastyreflect.KernelImpl.QuotedExpr_cast(KernelImpl.scala:1742)
[error]     |   at scala.tasty.reflect.QuotedOps$QuotedExprAPI.cast(QuotedOps.scala:13)
[error]     |   at dotty.xml.interpolator.internal.Expand$.expandAttributes$$anonfun$1(Expand.scala:86)
[error]     |   at scala.collection.immutable.List.$anonfun$foldRight$1(List.scala:408)
[error]     |   at scala.collection.immutable.List.foldRight(List.scala:89)
[error]     |   at dotty.xml.interpolator.internal.Expand$.expandAttributes(Expand.scala:90)
[error]     |   at dotty.xml.interpolator.internal.Expand$.expandElem(Expand.scala:44)
[error]     |   at dotty.xml.interpolator.internal.Expand$.expandNode(Expand.scala:22)
[error]     |   at dotty.xml.interpolator.internal.Expand$.apply(Expand.scala:15)
[error]     |   at dotty.xml.interpolator.internal.Macro$.$anonfun$5(Macro.scala:75)
[error]     |   at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
[error]     |   at dotty.xml.interpolator.internal.Macro$.implCore(Macro.scala:78)
[error]     |   at dotty.xml.interpolator.internal.Macro$.implErrors(Macro.scala:57)
```

**Comment by nicolasstucki** [comment]
Actually it only happens within `implErrors`
